# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64fccc679ccd7d8e8b2f5e71fb33353495347ae74043db2d597c676b49b289c6c9d336d7fdcd8d2a1d382771c5d7099ebbf783dd3ac0f4ec3941906ad6f2568
  facebook_app_id: 998612400185735
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 7d1c9d7fffd95c911ac547003f1428df881b4d4dfa2085a392dfef1518a47278e58c92623920d720cb201cd6d66f7f8cdddde6f2b095c68ea3f4df5f8e577bad
  facebook_app_id: 998612400185735
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 998612400185735
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
